
export const catalogo = [
    {
        id: 1,
        nome:"colar de pedras",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-1.jpeg",
    },
 {
        id: 2,
        nome:"colar de pedras",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-2.jpeg",
    },
 {
        id: 3,
        nome:"colar de pedra cristal",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-3.jpeg",
    },
 {
        id: 4,
        nome:"colar de pedrarias",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-4.jpeg",
    },
 {
        id: 5,
        nome:"colar de argolas",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-5.jpeg",
    },
 {
        id: 6,
        nome:"colar de pedras rosas",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-6.jpeg",
    },
 {
        id: 7,
        nome:"brinco de folhas",
        marca: "G-joyas",
        preço: 69.90,
        Imagem: "produto-7.jpeg",
    },
 {
        id: 8,
        nome:"colar de pedras coloridas",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-8.jpeg",
    },
 {
        id: 9,
        nome:"thocker",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-9.jpeg",
    },
 {
        id: 10,
        nome:"brinco de folhas",
        marca: "G-joyas",
        preço: 69.90,
        Imagem: "produto-10.jpeg",
    },
 {
        id: 11,
        nome:"thocker scamado",
        marca: "G-joyas",
        preço: 99.90,
       Imagem: "produto-11.jpeg",
    },
 {
        id: 12,
        nome:"brinco de folhas",
        marca: "G-joyas",
        preço: 79.90,
       Imagem: "produto-12.jpeg",
    },
 {
        id: 13,
        nome:"brincos  caracol",
        marca: "G-joyas",
        preço: 79.90,
        Imagem: "produto-13.jpeg",
    },
 {
        id: 14,
        nome:"brinco escamado",
        marca: "G-joyas",
        preço: 89.90,
       Imagem: "produto-14.jpeg",
    },
 {
        id: 15,
        nome:"colar de cruz",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-15.jpeg",
    },
 {
        id: 16,
        nome:"colar de argolas",
        marca: "G-joyas",
        preço: 99.90,
        Imagem: "produto-16.jpeg",
    },
 {
        id: 18,
        nome:"brinco coração",
        marca: "G-joyas",
        preço: 79.90,
        Imagem: "produto-18.jpeg",
    },
 {
        id: 19,
        nome:"brinco argolas finas",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-19.jpeg",
    },
 {
        id: 20,
        nome:"brincos canulados",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-20.jpeg",
    },
 {
        id: 21,
        nome:"brincos tri argolas",
        marca: "G-joyas",
        preço: 89.90,
        Imagem: "produto-21.jpeg",
    },

];